-- APP: triagens migrações SQL 

-- APP: triagens MIGRATION: 0001_initial
BEGIN;
--
-- Create model Triagem
--
CREATE TABLE "triagens_triagem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "data_hora_inicio" timestamp with time zone NOT NULL, "data_hora_fim" timestamp with time zone NULL, "status" varchar(20) NOT NULL, "observacoes_gerais" text NOT NULL, "paciente_id" bigint NOT NULL, "profissional_responsavel_id" bigint NULL);
--
-- Create model RespostaTriagem
--
CREATE TABLE "triagens_respostatriagem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "intensidade" smallint NOT NULL CHECK ("intensidade" >= 0), "duracao" varchar(120) NOT NULL, "possui_sinal_alerta" boolean NOT NULL, "observacao" text NOT NULL, "sintoma_id" bigint NOT NULL, "triagem_id" bigint NOT NULL);

ALTER TABLE "triagens_triagem" ADD CONSTRAINT "triagens_triagem_paciente_id_21798c6c_fk_pacientes_paciente_id" FOREIGN KEY ("paciente_id") REFERENCES "pacientes_paciente" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "triagens_triagem" ADD CONSTRAINT "triagens_triagem_profissional_respons_31d87f37_fk_usuarios_" FOREIGN KEY ("profissional_responsavel_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "triagens_triagem_paciente_id_21798c6c" ON "triagens_triagem" ("paciente_id");

CREATE INDEX "triagens_triagem_profissional_responsavel_id_31d87f37" ON "triagens_triagem" ("profissional_responsavel_id");

ALTER TABLE "triagens_respostatriagem" ADD CONSTRAINT "triagens_respostatriagem_triagem_id_sintoma_id_d96de7d7_uniq" UNIQUE ("triagem_id", "sintoma_id");

ALTER TABLE "triagens_respostatriagem" ADD CONSTRAINT "triagens_respostatri_sintoma_id_bd393044_fk_sintomas_" FOREIGN KEY ("sintoma_id") REFERENCES "sintomas_sintoma" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "triagens_respostatriagem" ADD CONSTRAINT "triagens_respostatri_triagem_id_53c11a1a_fk_triagens_" FOREIGN KEY ("triagem_id") REFERENCES "triagens_triagem" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "triagens_respostatriagem_sintoma_id_bd393044" ON "triagens_respostatriagem" ("sintoma_id");

CREATE INDEX "triagens_respostatriagem_triagem_id_53c11a1a" ON "triagens_respostatriagem" ("triagem_id");
COMMIT;


-- APP: triagens MIGRATION: 0002_remove_sinais_vitais_table
BEGIN;
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;


-- APP: pacientes MIGRATION: 0001_initial
BEGIN;
--
-- Create model Paciente
--
CREATE TABLE "pacientes_paciente" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nome_completo" varchar(200) NOT NULL, "data_nascimento" date NOT NULL, "sexo" varchar(20) NOT NULL, "cpf" varchar(14) NULL UNIQUE, "telefone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "endereco" varchar(255) NOT NULL, "alergias" text NOT NULL, "comorbidades" text NOT NULL, "medicamentos_em_uso" text NOT NULL, "contato_emergencia_nome" varchar(200) NOT NULL, "contato_emergencia_telefone" varchar(20) NOT NULL, "data_criacao" timestamp with time zone NOT NULL, "data_atualizacao" timestamp with time zone NOT NULL);

CREATE INDEX "pacientes_paciente_cpf_f48e0b43_like" ON "pacientes_paciente" ("cpf" varchar_pattern_ops);
COMMIT;


-- APP: pacientes MIGRATION: 0002_alter_paciente_data_nascimento
BEGIN;
--
-- Alter field data_nascimento on paciente
--
ALTER TABLE "pacientes_paciente" ALTER COLUMN "data_nascimento" DROP NOT NULL;
--
-- Alter field telefone on paciente
--
-- (no-op)
COMMIT;


-- APP: pacientes MIGRATION: 0003_paciente_usuario_auth
BEGIN;
--
-- Add field usuario_auth to paciente
--
ALTER TABLE "pacientes_paciente" ADD COLUMN "usuario_auth_id" integer NULL UNIQUE CONSTRAINT "pacientes_paciente_usuario_auth_id_8c341af5_fk_auth_user_id" REFERENCES "auth_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "pacientes_paciente_usuario_auth_id_8c341af5_fk_auth_user_id" IMMEDIATE;

COMMIT;


-- APP: encaminhamentos MIGRATION: 0001_initial
BEGIN;
--
-- Create model Encaminhamento
--
CREATE TABLE "encaminhamentos_encaminhamento" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "recomendacao" varchar(20) NOT NULL, "descricao" text NOT NULL, "prazo_recomendado" varchar(120) NOT NULL, "data_geracao" timestamp with time zone NOT NULL, "triagem_id" bigint NOT NULL UNIQUE);

ALTER TABLE "encaminhamentos_encaminhamento" ADD CONSTRAINT "encaminhamentos_enca_triagem_id_95979a76_fk_triagens_" FOREIGN KEY ("triagem_id") REFERENCES "triagens_triagem" ("id") DEFERRABLE INITIALLY DEFERRED;

COMMIT;


-- APP: encaminhamentos MIGRATION: 0002_alter_encaminhamento_recomendacao_agendaprofissional
BEGIN;
--
-- Alter field recomendacao on encaminhamento
--
-- (no-op)
--
-- Create model AgendaProfissional
--
CREATE TABLE "encaminhamentos_agendaprofissional" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "especialidade" varchar(32) NOT NULL, "inicio_atendimento" timestamp with time zone NOT NULL, "fim_atendimento" timestamp with time zone NOT NULL, "reservado" boolean NOT NULL, "ativo" boolean NOT NULL, "profissional_id" bigint NOT NULL);
--
-- Create model PreAgendamento
--
CREATE TABLE "encaminhamentos_preagendamento" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "especialidade" varchar(32) NOT NULL, "horario_sugerido" timestamp with time zone NULL, "status" varchar(32) NOT NULL, "mensagem" text NOT NULL, "data_geracao" timestamp with time zone NOT NULL, "data_atualizacao" timestamp with time zone NOT NULL, "encaminhamento_id" bigint NOT NULL UNIQUE, "profissional_id" bigint NULL, "triagem_id" bigint NOT NULL UNIQUE);

ALTER TABLE "encaminhamentos_agendaprofissional" ADD CONSTRAINT "encaminhamentos_agen_profissional_id_5cda19db_fk_usuarios_" FOREIGN KEY ("profissional_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "encaminhamentos_agendaprofissional_profissional_id_5cda19db" ON 
"encaminhamentos_agendaprofissional" ("profissional_id");

ALTER TABLE "encaminhamentos_preagendamento" ADD CONSTRAINT "encaminhamentos_prea_encaminhamento_id_7002c646_fk_encaminha" FOREIGN KEY ("encaminhamento_id") REFERENCES "encaminhamentos_encaminhamento" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "encaminhamentos_preagendamento" ADD CONSTRAINT "encaminhamentos_prea_profissional_id_ef6ebd62_fk_usuarios_" FOREIGN KEY ("profissional_id") REFERENCES "usuarios_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "encaminhamentos_preagendamento" ADD CONSTRAINT "encaminhamentos_prea_triagem_id_958c9575_fk_triagens_" FOREIGN KEY ("triagem_id") REFERENCES "triagens_triagem" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "encaminhamentos_preagendamento_profissional_id_ef6ebd62" ON "encaminhamentos_preagendamento" ("profissional_id");
COMMIT;


-- APP: encaminhamentos MIGRATION: 0003_preagendamento_agenda_slot
BEGIN;
--
-- Add field agenda_slot to preagendamento
--
ALTER TABLE "encaminhamentos_preagendamento" ADD COLUMN "agenda_slot_id" bigint NULL CONSTRAINT "encaminhamentos_prea_agenda_slot_id_28609f22_fk_encaminha" REFERENCES "encaminhamentos_agendaprofissional"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "encaminhamentos_prea_agenda_slot_id_28609f22_fk_encaminha" IMMEDIATE;
--
-- Alter field status on preagendamento
--
-- (no-op)
CREATE INDEX "encaminhamentos_preagendamento_agenda_slot_id_28609f22" ON "encaminhamentos_preagendamento" ("agenda_slot_id");
COMMIT;


-- APP: sintomas MIGRATION: 0001_initial
BEGIN;
--
-- Create model Sintoma
--
CREATE TABLE "sintomas_sintoma" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nome" varchar(120) NOT NULL UNIQUE, "descricao" text NOT NULL, "ativo" boolean NOT NULL);

CREATE INDEX "sintomas_sintoma_nome_5a13af3e_like" ON "sintomas_sintoma" ("nome" varchar_pattern_ops);

COMMIT;


-- APP: classificacao_risco MIGRATION: 0001_initial
BEGIN;
--
-- Create model ClassificacaoRisco
--
CREATE TABLE "classificacao_risco_classificacaorisco" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nivel" varchar(20) NOT NULL, "pontuacao" smallint NOT NULL CHECK ("pontuacao" >= 0), "justificativa" text NOT NULL, "protocolo_versao" varchar(30) NOT NULL, "data_classificacao" timestamp with time zone NOT NULL, "triagem_id" bigint NOT NULL UNIQUE);

ALTER TABLE "classificacao_risco_classificacaorisco" ADD CONSTRAINT "classificacao_risco__triagem_id_64ce3bbc_fk_triagens_" FOREIGN KEY ("triagem_id") REFERENCES "triagens_triagem" ("id") DEFERRABLE INITIALLY DEFERRED;

COMMIT;


-- APP: usuarios MIGRATION: 0001_initial
BEGIN;
--
-- Create model Usuario
--
CREATE TABLE "usuarios_usuario" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nome_completo" varchar(200) NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "perfil" varchar(20) NOT NULL, "ativo" boolean NOT NULL, "data_criacao" timestamp with time zone NOT NULL, "data_atualizacao" timestamp with time zone NOT NULL, "usuario_auth_id" integer NULL UNIQUE);

ALTER TABLE "usuarios_usuario" ADD CONSTRAINT "usuarios_usuario_usuario_auth_id_7f933b31_fk_auth_user_id" FOREIGN KEY ("usuario_auth_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "usuarios_usuario_email_0a82e5f9_like" ON "usuarios_usuario" ("email" varchar_pattern_ops);
COMMIT;


-- APP: usuarios MIGRATION: 0002_alter_usuario_especialidade
BEGIN;
--
-- Add field especialidade to usuario
--
ALTER TABLE "usuarios_usuario" ADD COLUMN "especialidade" varchar(32) DEFAULT '' NOT NULL;

ALTER TABLE "usuarios_usuario" ALTER COLUMN "especialidade" DROP DEFAULT;
--
-- Alter field perfil on usuario
--
-- (no-op)
COMMIT;


