# Generated by Django 5.2.14 on 2026-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('clinica_geral', 'Clinica Geral'), ('cardiologia', 'Cardiologia'), ('neurologia', 'Neurologia'), ('pneumologia', 'Pneumologia'), ('gastroenterologia', 'Gastroenterologia')], default='', help_text='Aplicavel principalmente para perfis profissionais.', max_length=32),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('profissional', 'Profissional de Saude'), ('paciente', 'Paciente')], max_length=20),
        ),
    ]
