# Generated by Django 5.2.14 on 2026-05-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacao', models.CharField(choices=[('autocuidado', 'Autocuidado'), ('consulta', 'Consulta agendada'), ('urgencia', 'Buscar urgência'), ('emergencia', 'Acionar emergência')], max_length=20)),
                ('descricao', models.TextField()),
                ('prazo_recomendado', models.CharField(blank=True, max_length=120)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('triagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamento', to='triagens.triagem')),
            ],
            options={
                'verbose_name': 'Encaminhamento',
                'verbose_name_plural': 'Encaminhamentos',
            },
        ),
    ]
