# Generated by Django 5.2.14 on 2026-05-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0001_initial'),
        ('triagens', '0002_remove_sinais_vitais_table'),
        ('usuarios', '0002_alter_usuario_options_usuario_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='recomendacao',
            field=models.CharField(choices=[('autocuidado', 'Autocuidado'), ('consulta', 'Consulta agendada'), ('urgencia', 'Buscar urgencia'), ('emergencia', 'Acionar emergencia')], max_length=20),
        ),
        migrations.CreateModel(
            name='AgendaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('clinica_geral', 'Clinica Geral'), ('cardiologia', 'Cardiologia'), ('neurologia', 'Neurologia'), ('pneumologia', 'Pneumologia'), ('gastroenterologia', 'Gastroenterologia')], max_length=32)),
                ('inicio_atendimento', models.DateTimeField()),
                ('fim_atendimento', models.DateTimeField()),
                ('reservado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_profissional', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Agenda de Profissional',
                'verbose_name_plural': 'Agendas de Profissionais',
                'ordering': ['inicio_atendimento'],
            },
        ),
        migrations.CreateModel(
            name='PreAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, default='', max_length=32)),
                ('horario_sugerido', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sugerido', 'Sugerido'), ('sem_vaga', 'Sem vaga'), ('encaminhamento_direto', 'Encaminhamento direto')], default='sem_vaga', max_length=32)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('encaminhamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_agendamento', to='encaminhamentos.encaminhamento')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_agendamentos_sugeridos', to='usuarios.usuario')),
                ('triagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_agendamento', to='triagens.triagem')),
            ],
            options={
                'verbose_name': 'Pre-agendamento',
                'verbose_name_plural': 'Pre-agendamentos',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
