# Generated by Django 5.2.14 on 2026-05-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0002_alter_encaminhamento_recomendacao_agendaprofissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preagendamento',
            name='agenda_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_agendamentos', to='encaminhamentos.agendaprofissional'),
        ),
        migrations.AlterField(
            model_name='preagendamento',
            name='status',
            field=models.CharField(choices=[('sugerido', 'Sugerido'), ('confirmado', 'Confirmado'), ('reagendado', 'Reagendado'), ('cancelado', 'Cancelado'), ('sem_vaga', 'Sem vaga'), ('encaminhamento_direto', 'Encaminhamento direto')], default='sem_vaga', max_length=32),
        ),
    ]
