# Generated by Django 5.2.14 on 2026-05-13 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('sintomas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triagens', to='pacientes.paciente')),
                ('profissional_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens_realizadas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Triagem',
                'verbose_name_plural': 'Triagens',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RespostaTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidade', models.PositiveSmallIntegerField(help_text='Escala de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('duracao', models.CharField(max_length=120)),
                ('possui_sinal_alerta', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='sintomas.sintoma')),
                ('triagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='triagens.triagem')),
            ],
            options={
                'verbose_name': 'Resposta de Triagem',
                'verbose_name_plural': 'Respostas de Triagem',
                'unique_together': {('triagem', 'sintoma')},
            },
        ),
    ]
