# Generated by Django 5.2.14 on 2026-05-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('emergencia', 'Emergência')], max_length=20)),
                ('pontuacao', models.PositiveSmallIntegerField(default=0)),
                ('justificativa', models.TextField()),
                ('protocolo_versao', models.CharField(default='v1', max_length=30)),
                ('data_classificacao', models.DateTimeField(auto_now_add=True)),
                ('triagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao_risco', to='triagens.triagem')),
            ],
            options={
                'verbose_name': 'Classificação de Risco',
                'verbose_name_plural': 'Classificações de Risco',
            },
        ),
    ]
